[package]
name = "accessfs-store"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
accessfs-core = { workspace = true }
age = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
zeroize = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
