[package]
name = "accessfs-discover"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
accessfs-catalog = { workspace = true }
accessfs-surface = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }
notify = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }
