[package]
name = "accessfs-platform"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
accessfs-core = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
libproc = { workspace = true }
libc = { workspace = true }
core-foundation = "0.10"
core-foundation-sys = "0.8"
