[package]
name = "accessfs-control"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
accessfs-catalog = { workspace = true }
accessfs-store = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
