[package]
name = "floria-replication"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
age = { workspace = true }
base64 = { workspace = true }
ed25519-dalek = { workspace = true }
floria-catalog = { workspace = true }
floria-integrity = { workspace = true }
floria-store = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
signature = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
