[package]
name = "accessfs-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }
dashmap = { workspace = true }
globset = { workspace = true }
humantime = { workspace = true }
wait-timeout = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
